
# Mesh geometry and texture
Mesh:
  mesh_file: "bloodfalls"
  mesh_texture_file: "bloodfalls.jpg"
  translation: [0,0,0]
  rotation: [[1,0,0], [0,0.71,-0.71], [0,0.71,0.71]] # rotation matrix (rotation +45 around x axis)
  scale: 1


Sites: # Sampling site locations for particular scene
  camera_locs: [[0,12,-10.98]]
