
# Mesh geometry and texture
Mesh:
  mesh_file: "Site_A1_simplified_3d_mesh"
  mesh_texture_file: "Site_A1_texture.jpg"
  translation: [0,0,0]
  rotation: [[1,0,0], [0,1,0], [0,0,1]] # rotation matrix
  scale: 1

Sites: # Sampling site locations for particular scene
  camera_locs: [[-12.0, -5.0, -2.0]]