SunLight:
  angular_diameter: 0.01
  energy: 4.14
  rotation:
  - 0
  - 0
  - 0
  translation:
  - 0
  - 0
  - 10
Terrain:
  mesh_name: gaea_ridgy_terrain
Textures:
  Albedo_RGB:
  - 0.8
  - 0.8
  - 0.8
  - 1.0
  Metallic: 0.0
  Roughness: 0.5
  Specular: 0.5
  Subsurface_Fac: 0.0
  Transmission: 0.0
  folder: images/
  mesh_disp_file: null
  mesh_normal_file: null
  mesh_roughness_file: null
  mesh_texture_file: icy-textures/aaron-burden-2GwUjTNX1CE-unsplash.jpg
  mesh_transmission_file: null
dataset_type: gaea_texture_variation
demo: True
outputIdentifier: 'ex'
